var carsen = [
    "\"Raising funds\" for your set at Astrub Zaap",
    "Adapting the latest trends to your own style",
    "Analyzing your colors",
    "Asking a friend tailor to alter some pieces",
    "Asking for advice at the salon",
    "Asking the Astrub shoemakers for thongs",
    "Bargaining for colorful accessories",
    "Bargaining for pirate rings at Madrestam harbor",
    "Browsing Brakmar's shoemaker's shop",
    "Browsing the markets for formal wear",
    "Buying perfect fit shoes at Bonta shoemakers'",
    "Checking Astrub jeweller's market for bargains",
    "Checking if what we have so far looks good together",
    "Checking out swimming suits at Sufokia's marketplace",
    "Checking out your closet",
    "Choosing a good outfit coordination",
    "Choosing clothes that make your silhouette appear balanced",
    "Combining different sets",
    "Considering all amulets",
    "Considering all belts",
    "Considering all boots",
    "Considering all cloaks",
    "Considering all dofuses",
    "Considering all hats",
    "Considering all rings",
    "Considering all weapons",
    "Considering if maybe you just need a shower",
    "Crushing your current gear for runes",
    "Debating if you should be 1/2 crit",
    "Debating whether to suggest a face change potion",
    "Debating whether to suggest a sex change potion",
    "Drawing sketches",
    "Drooling over the amazing items and outrageous prices at Amakna Village",
    "Explaning you it's not about having 12 AP, but about looking good",
    "Farming kitsous frantically for Ra Vits",
    "Figuring out your body shape",
    "Finding out why no one wears that hat",
    "Finding out about your style",
    "Finding the perfect shield to go with that",
    "Finding the right clothing cut and style",
    "Forbidding you from ever wearing that hat again",
    "Getting a cursed necklace at Brakmar",
    "Getting advice from the town drunk at the inn",
    "Getting advice from a stylist",
    "Getting advice from the Village's great tailors",
    "Getting anxious with items' draconian conditions",
    "Getting inspiration from the street style at the Village",
    "Getting some wardrobe essentials",
    "Getting the Village shoemaker to craft you a custom-made belt",
    "Getting warm boots with Frigost's shoemakers",
    "Getting winter clothes advice at Frigost's tailor workshop",
    "Going for a cuter look",
    "Going for a fiercer look",
    "Going on a shopping spree",
    "Having a cloak hemmed",
    'Helping you mount a Karmeleon',
    "Hunting Leopardos",
    "Inquiring Brakmar tailors",
    "Looking at the accessories you already have",
    "Looking for a fabulous cloak at the tailor markets",
    "Looking for a pair of rings at Bonta jeweller's market",
    "Looking for good combos at the journal",
    "Looking for outfits at the portfolio",
    "Looking for something sparkly at Frigost Village's marketplace",
    "Looking for suggestions on the internet",
    "Making a composition with different fabrics",
    "Matching a weapon with the rest of the gear",
    "Measuring out your shoulder size and angle",
    "Measuring your height",
    "Measuring your neck length and circumference",
    "Measuring your waist line",
    "Meditating on your impossible requirements",
    "Messaging a friend shoemaker for fabulous shoes suggestions",
    "Mixing different colors",
    "Mixing different shapes",
    "Observing the street style at the tailors' quarter",
    "Ordering a potion to make you pretty",
    "Overhauling your wardrobe",
    "Paying a visit to famous Bonta tailors",
    "Picking a shiny amulet with a friend jeweller",
    "Picking pieces that accentuate your best features and disguise the rest",
    "PM'ing random people to open Kralove",
    "Putting everything together",
    "Putting together a proportional outfit",
    "Polishing your boots",
    "Reading about the latest trends",
    "Reading fashion magazines",
    "Reassuring that you don't look bad from ALL angles",
    'Removing the price tags before your spouse sees them',
    "Searching for pieces that accentuate your body's flattering spots",
    "Searching for ways to hide your bad spots",
    "Searching for the perfect ring at the Village",
    "Selecting rare forgotten pieces at Astrub's shoemaker's market",
    "Sighing at how you can use all those trophies having never won a Kolo",
    "Studying fashion guidelines",
    "Studying what would go well with Gobball Leather",
    "Summing up attributes",
    "Switching the hat",
    "Taking an x-ray to see your bone structure",
    "Taking precious stones to craft rings at the jewellers' quarter",
    "Taking you to the bank to get a loan",
    "Taking your body measurements",
    "Thinking about referring you to a proper stylist",
    "Thinking maybe you need a color change potion",
    "Throwing everything away and starting over",
    "Trying on getas at Pandala Suburbs marketplace",
    "Trying out a basic black",
    "Trying out some never made combinations",
    "Trying to save something from your old set",
    "Visiting a stylist friend",
    "Visiting the best Astrub tailor",
    "Wondering if you like fur",
    "Wondering if you like plumes",
    "Wondering if you really need that much wisdom",
    "Wondering if you would mind wearing slippers all the time",
    "Wondering what haircut you should get",
    "Wondering whether you are capable of keeping a pet alive"
];

var carsfr = [
    "\"Collecter des fonds\" pour votre ensemble à Astrub Zaap",
    "Adapter les dernières tendances à votre propre style",
    "Analyser vos couleurs",
    "Demander à un ami tailleur de modifier quelques pièces",
    "Demander des conseils au salon",
    "Demander des tongs aux cordonniers d'Astrub",
    "Négocier pour des accessoires colorés",
    "Négocier pour des anneaux de pirate au port de Madrestam",
    "Parcourir la boutique du cordonnier de Brakmar",
    "Chercher des tenues formelles sur les marchés",
    "Acheter des chaussures parfaitement ajustées chez les cordonniers de Bonta",
    "Vérifier le marché des bijoutiers d'Astrub pour les bonnes affaires",
    "Vérifier si ce que nous avons jusqu'à présent va bien ensemble",
    "Regarder les maillots de bain sur le marché de Sufokia",
    "Vérifier votre placard",
    "Choisir une bonne coordination de tenue",
    "Choisir des vêtements qui équilibrent votre silhouette",
    "Combiner différents ensembles",
    "Envisager tous les amulettes",
    "Envisager toutes les ceintures",
    "Envisager toutes les bottes",
    "Envisager toutes les capes",
    "Envisager tous les dofus",
    "Envisager tous les chapeaux",
    "Envisager toutes les anneaux",
    "Envisager toutes les armes",
    "Se demander si peut-être vous avez juste besoin d'une douche",
    "Écraser votre équipement actuel pour des runes",
    "Débattre si vous devriez être à 1/2 en critique",
    "Débattre pour proposer ou non une potion de changement de visage",
    "Débattre pour proposer ou non une potion de changement de sexe",
    "Faire des esquisses",
    "Saliver sur les objets incroyables et les prix exorbitants au Village d'Amakna",
    "Vous expliquer qu'il ne s'agit pas d'avoir 12 PA, mais de bien paraître",
    "Faire de l'agriculture frénétique de kitsous pour des Ra Vits",
    "Déterminer la forme de votre corps",
    "Découvrir pourquoi personne ne porte ce chapeau",
    "Découvrir votre style",
    "Trouver le bouclier parfait pour aller avec ça",
    "Trouver le bon style et la bonne coupe de vêtements",
    "Vous interdire de jamais porter ce chapeau à nouveau",
    "Obtenir un collier maudit à Brakmar",
    "Obtenir des conseils du poivrot de la ville à l'auberge",
    "Obtenir des conseils d'un styliste",
    "Obtenir des conseils des grands tailleurs du Village",
    "Devenir anxieux avec les conditions draconiennes des objets",
    "Trouver l'inspiration dans le style de rue du Village",
    "Obtenir des éléments essentiels pour la garde-robe",
    "Faire fabriquer une ceinture sur mesure par le cordonnier du Village",
    "Obtenir des bottes chaudes auprès des cordonniers de Frigost",
    "Demander des conseils sur les vêtements d'hiver à l'atelier de tailleur de Frigost",
    "Opter pour un look plus mignon",
    "Opter pour un look plus féroce",
    "Faire une virée shopping",
    "Faire ourler une cape",
    "Vous aider à monter un Karméléon",
    "Chasser des Léopardos",
    "S'informer auprès des tailleurs de Brakmar",
    "Regarder les accessoires que vous avez déjà",
    "Chercher une cape fabuleuse sur les marchés de tailleur",
    "Chercher une paire d'anneaux au marché des bijoutiers de Bonta",
    "Rechercher de bonnes combinaisons dans le journal",
    "Chercher des tenues dans le portfolio",
    "Chercher quelque chose de pétillant sur le marché du village de Frigost",
    "Chercher des suggestions sur Internet",
    "Faire une composition avec différents tissus",
    "Assortir une arme avec le reste de l'équipement",
    "Mesurer la taille et l'angle de vos épaules",
    "Mesurer votre taille",
    "Mesurer la longueur et la circonférence de votre cou",
    "Mesurer votre tour de taille",
    "Méditer sur vos exigences impossibles",
    "Envoyer un message à un ami cordonnier pour des suggestions de chaussures fabuleuses",
    "Mélanger différentes couleurs",
    "Mélanger différentes formes",
    "Observer le style de rue dans le quartier des tailleurs",
    "Commander une potion pour vous rendre joli",
    "Refaire votre garde-robe",
    "Rendre visite aux célèbres tailleurs de Bonta",
    "Choisir un amulette brillante avec un ami bijoutier",
    "Choisir des pièces qui mettent en valeur vos meilleurs atouts et camouflent le reste",
    "Envoyer des MP à des personnes aléatoires pour ouvrir Kralove",
    "Assembler le tout",
    "Composer une tenue proportionnelle",
    "Polir vos bottes",
    "Lire sur les dernières tendances",
    "Lire des magazines de mode",
    "Vous rassurer que vous n'avez pas l'air mauvais sous TOUS les angles",
    "Retirer les étiquettes de prix avant que votre conjoint les voie",
    "Rechercher des pièces qui mettent en valeur les parties flatteuses de votre corps",
    "Rechercher des moyens de cacher vos défauts",
    "Chercher l'anneau parfait au Village",
    "Sélectionner des pièces rares oubliées au marché des cordonniers d'Astrub",
    "Soupirer en pensant à comment vous pouvez utiliser tous ces trophées sans jamais avoir gagné un Kolo",
    "Étudier les directives de mode",
    "Étudier ce qui irait bien avec du cuir de Bouftou",
    "Résumer les attributs",
    "Changer le chapeau",
    "Passer une radiographie pour voir votre structure osseuse"
];

var carses = [
    "\"Recaudando fondos\" para tu equipo en el Zaap de Astrub",
    "Adaptando las últimas tendencias a tu propio estilo",
    "Analizando tus colores",
    "Pidiendo a un amigo sastre que ajuste algunas piezas",
    "Consultando en el salón de belleza",
    "Pidiendo chanclas a los zapateros de Astrub",
    "Regateando por accesorios coloridos",
    "Regateando por anillos de pirata en el puerto de Madrestam",
    "Explorando la zapatería de Brakmar",
    "Buscando en los mercados ropa formal",
    "Comprando zapatos a medida en la zapatería de Bonta",
    "Verificando el mercado de joyeros de Astrub en busca de ofertas",
    "Comprobando si lo que tenemos hasta ahora se ve bien en conjunto",
    "Mirando trajes de baño en el mercado de Sufokia",
    "Revisando tu armario",
    "Eligiendo una buena coordinación de vestuario",
    "Escogiendo ropa que haga que tu silueta parezca equilibrada",
    "Combinando diferentes conjuntos",
    "Considerando todos los amuletos",
    "Considerando todos los cinturones",
    "Considerando todas las botas",
    "Considerando todas las capas",
    "Considerando todos los dofus",
    "Considerando todos los sombreros",
    "Considerando todos los anillos",
    "Considerando todas las armas",
    "Pensando si quizás solo necesitas una ducha",
    "Desmenuzando tu equipo actual por runas",
    "Debatiendo si deberías tener 1/2 en críticos",
    "Debatiendo si sugerir una poción para cambiar de cara",
    "Debatiendo si sugerir una poción para cambiar de sexo",
    "Dibujando bocetos",
    "Babeando por los increíbles objetos y los precios exorbitantes en la Aldea de Amakna",
    "Explicándote que no se trata de tener 12 PA, sino de verte bien",
    "Cosechando kitsous frenéticamente por Ra Vits",
    "Descubriendo tu forma de cuerpo",
    "Averiguando por qué nadie lleva ese sombrero",
    "Descubriendo tu estilo",
    "Encontrando el escudo perfecto para combinar",
    "Encontrando el corte y estilo de ropa adecuados",
    "Prohibiéndote que vuelvas a llevar ese sombrero",
    "Consiguiendo un collar maldito en Brakmar",
    "Obteniendo consejo del borracho del pueblo en la posada",
    "Obteniendo consejos de un estilista",
    "Obteniendo consejos de los grandes sastres de la Aldea",
    "Poniéndote ansioso con las draconianas condiciones de los objetos",
    "Inspirándote en el estilo callejero de la Aldea",
    "Consiguiendo algunos elementos esenciales para el armario",
    "Haciendo que el zapatero de la Aldea te haga un cinturón a medida",
    "Consiguiendo botas abrigadas con los zapateros de Frigost",
    "Obteniendo consejos para ropa de invierno en el taller de sastres de Frigost",
    "Optando por un look más adorable",
    "Optando por un look más feroz",
    "Yéndote de compras a lo grande",
    "Haciendo el dobladillo a una capa",
    "Ayudándote a montar un Karmeleón",
    "Cazando Leopardos",
    "Consultando a los sastres de Brakmar",
    "Mirando los accesorios que ya tienes",
    "Buscando una capa fabulosa en los mercados de sastres",
    "Buscando un par de anillos en el mercado de joyeros de Bonta",
    "Buscando buenas combinaciones en el periódico",
    "Buscando trajes en el portafolio",
    "Buscando algo brillante en el mercado de la aldea de Frigost",
    "Buscando sugerencias en internet",
    "Haciendo una composición con diferentes tejidos",
    "Emparejando una arma con el resto del equipo",
    "Midiendo el tamaño y el ángulo de tus hombros",
    "Midiendo tu altura",
    "Midiendo la longitud y la circunferencia de tu cuello",
    "Midiendo tu cintura",
    "Meditando sobre tus requisitos imposibles",
    "Enviando un mensaje a un amigo zapatero para sugerencias de zapatos fabulosos",
    "Mezclando diferentes colores",
    "Mezclando diferentes formas",
    "Observando el estilo callejero en el barrio de los sastres",
    "Pidiendo una poción para hacerte bonito",
    "Renovando tu armario",
    "Visitando a los famosos sastres de Bonta",
    "Escogiendo un amuleto brillante con un amigo joyero",
    "Escogiendo piezas que acentúen tus mejores características y disimulen el resto",
    "Enviando mensajes privados a gente al azar para abrir Kralove",
    "Juntándolo todo",
    "Armando un atuendo proporcional",
    "Pulir tus botas",
    "Leyendo sobre las últimas tendencias",
    "Leyendo revistas de moda",
    "Asegurándote de que no te ves mal desde TODOS los ángulos",
    "Quitando las etiquetas de precio antes de que tu cónyuge las vea",
    "Buscando piezas que resalten los puntos favorecedores de tu cuerpo",
    "Buscando formas de ocultar tus defectos",
    "Buscando el anillo perfecto en la Aldea",
    "Seleccionando piezas olvidadas y raras en el mercado de zapateros de Astrub",
    "Suspirando sobre cómo puedes usar todos esos trofeos sin haber ganado nunca un Kolo",
    "Estudiando pautas de moda",
    "Estudiando qué iría bien con Cuero de Jalató",
    "Resumiendo atributos",
    "Cambiando el sombrero",
    "Tomando una radiografía para ver tu estructura ósea",
    "Llevando piedras preciosas para hacer anillos en el barrio de los joyeros",
    "Llevándote al banco para conseguir un préstamo",
    "Tomando tus medidas corporales",
    "Pensando en referirte a un estilista adecuado",
    "Pensando que quizás necesites una poción para cambiar de color",
    "Tirándolo todo y empezando de nuevo",
    "Probándote getas en el mercado de las afueras de Pandala",
    "Probando un negro básico",
    "Probando algunas combinaciones nunca hechas",
    "Intentando salvar algo de tu antiguo conjunto",
    "Visitando a un amigo estilista",
    "Visitando al mejor sastre de Astrub",
    "Preguntándose si te gusta el pelo",
    "Preguntándose si te gustan las plumas",
    "Preguntándose si realmente necesitas tanta sabiduría",
    "Preguntándose si te importaría llevar zapatillas todo el tiempo",
    "Preguntándose qué corte de pelo deberías tener",
    "Preguntándose si eres capaz de mantener una mascota con vida"
];

var carspt = [
    "\"Arrecadando fundos\" para o seu conjunto no Zaap de Astrub",
    "Adaptando as últimas tendências ao seu próprio estilo",
    "Analisando suas cores",
    "Pedindo a um amigo alfaiate para ajustar algumas peças",
    "Pedindo conselhos no salão",
    "Pedindo aos sapateiros de Astrub por chinelos",
    "Negociando por acessórios coloridos",
    "Negociando por anéis de pirata no porto de Madrestam",
    "Passeando pela loja do sapateiro de Brakmar",
    "Explorando os mercados por roupas formais",
    "Comprando sapatos perfeitamente ajustados na sapataria de Bonta",
    "Checando o mercado de joalheiros de Astrub por barganhas",
    "Verificando se o que temos até agora fica bom junto",
    "Conferindo trajes de banho no mercado de Sufokia",
    "Analisando seu armário",
    "Escolhendo uma boa coordenação de roupa",
    "Escolhendo roupas que fazem sua silhueta parecer equilibrada",
    "Combinando diferentes conjuntos",
    "Considerando todos os amuletos",
    "Considerando todos os cintos",
    "Considerando todas as botas",
    "Considerando todas as capas",
    "Considerando todos os dofuses",
    "Considerando todos os chapéus",
    "Considerando todos os anéis",
    "Considerando todas as armas",
    "Pensando se talvez você só precise de um banho",
    "Destruindo seu equipamento atual por runas",
    "Debatendo se você deve ter 1/2 de crit",
    "Debatendo se deve sugerir uma poção de mudança de rosto",
    "Debatendo se deve sugerir uma poção de mudança de sexo",
    "Fazendo esboços",
    "Babando pelos itens incríveis e preços exorbitantes na Vila de Amakna",
    "Explicando que não se trata de ter 12 PA, mas de parecer bom",
    "Coletando kitsous freneticamente por Ra Vits",
    "Descobrindo o formato do seu corpo",
    "Descobrindo por que ninguém usa aquele chapéu",
    "Descobrindo sobre o seu estilo",
    "Encontrando o escudo perfeito para combinar",
    "Encontrando o corte e estilo de roupa certo",
    "Proibindo você de usar aquele chapéu novamente",
    "Conseguindo um colar amaldiçoado em Brakmar",
    "Recebendo conselhos do bêbado da cidade na estalagem",
    "Recebendo conselhos de um estilista",
    "Recebendo conselhos dos grandes alfaiates da Vila",
    "Ficando ansioso com as condições draconianas dos itens",
    "Buscando inspiração no estilo de rua da Vila",
    "Conseguindo alguns itens essenciais do guarda-roupa",
    "Pedindo ao sapateiro da Vila para criar um cinto sob medida",
    "Comprando botas quentes com os sapateiros de Frigost",
    "Recebendo conselhos de roupas de inverno na oficina de alfaiate de Frigost",
    "Optando por um visual mais fofo",
    "Optando por um visual mais feroz",
    "Indo às compras loucamente",
    "Ajustando a bainha de uma capa",
    "Ajudando você a montar um Karmeleon",
    "Caçando Leopardos",
    "Consultando alfaiates de Brakmar",
    "Olhando os acessórios que você já tem",
    "Procurando uma capa fabulosa nos mercados de alfaiate",
    "Procurando um par de anéis no mercado de joalheiros de Bonta",
    "Procurando boas combinações no jornal",
    "Procurando conjuntos no portfólio",
    "Procurando algo brilhante no mercado da Vila de Frigost",
    "Procurando sugestões na internet",
    "Fazendo uma composição com diferentes tecidos",
    "Combinando uma arma com o resto do equipamento",
    "Medindo o tamanho e o ângulo do seu ombro",
    "Medindo sua altura",
    "Medindo o comprimento e a circunferência do seu pescoço",
    "Medindo sua cintura",
    "Meditando sobre suas exigências impossíveis",
    "Mensageando um amigo sapateiro para sugestões de sapatos fabulosos",
    "Misturando diferentes cores",
    "Misturando diferentes formas",
    "Observando o estilo de rua no bairro dos alfaiates",
    "Encomendando uma poção para te deixar bonito",
    "Revitalizando seu guarda-roupa",
    "Fazendo uma visita aos famosos alfaiates de Bonta",
    "Escolhendo um amuleto brilhante com um amigo joalheiro",
    "Escolhendo peças que realçam suas melhores características e disfarçam o resto",
    "Mandando PM para pessoas aleatórias para abrir Kralove",
    "Juntando tudo",
    "Montando um conjunto proporcional",
    "Polindo suas botas",
    "Lendo sobre as últimas tendências",
    "Lendo revistas de moda",
    "Garantindo que você não parece ruim de TODOS os ângulos",
    "Retirando as etiquetas de preço antes que seu cônjuge as veja",
    "Procurando peças que realcem os pontos positivos do seu corpo",
    "Procurando maneiras de esconder seus pontos negativos",
    "Procurando pelo anel perfeito na Vila",
    "Selecionando peças raras esquecidas no mercado de sapateiros de Astrub",
    "Suspirando sobre como você pode usar todos esses troféus nunca tendo ganho um Kolo",
    "Estudando diretrizes de moda",
    "Estudando o que combinaria com Couro de Gobball",
    "Somando atributos",
    "Trocando o chapéu",
    "Tirando um raio-x para ver sua estrutura óssea",
    "Levando pedras preciosas para fazer anéis no bairro dos joalheiros",
    "Levando você ao banco para conseguir um empréstimo",
    "Tirando suas medidas corporais",
    "Pensando em encaminhá-lo a um estilista de verdade",
    "Pensando que talvez você precise de uma poção para mudar de cor",
    "Jogando tudo fora e começando de novo",
    "Experimentando getas no mercado dos subúrbios de Pandala",
    "Experimentando um preto básico",
    "Testando algumas combinações nunca feitas",
    "Tentando salvar algo do seu conjunto antigo",
    "Visitando um amigo estilista",
    "Visitando o melhor alfaiate de Astrub",
    "Perguntando-se se você gosta de pele",
    "Perguntando-se se você gosta de plumas",
    "Perguntando-se se você realmente precisa de tanta sabedoria",
    "Perguntando-se se você se importaria de usar chinelos o tempo todo",
    "Ponderando que corte de cabelo você deveria fazer",
    "Ponderando se você é capaz de manter um animal de estimação vivo"
];
            
function getRandomSentence(language) {
    let sentences;

    switch(language) {
        case 'en':
            sentences = carsen;
            break;
        case 'fr':
            sentences = carsfr;
            break;
        case 'es':
            sentences = carses;
            break;
        case 'pt':
            sentences = carspt;
            break;
        default:
            return '';
    }

    var index = Math.floor(Math.random() * sentences.length);
    var sentence = sentences[index];
    return sentence;
}

