# Generated by Django 4.2.6 on 2025-11-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chardata', '0008_alter_char_id_alter_char_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='char',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
