# Generated by Django 4.2.6 on 2025-11-04 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chardata', '0009_char_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('like', 'Like'), ('favorite', 'Favorite')], max_length=10)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chardata.char')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['build', 'vote_type'], name='chardata_bu_build_i_be05d1_idx'), models.Index(fields=['user', 'vote_type'], name='chardata_bu_user_id_f8cea4_idx')],
                'unique_together': {('user', 'build', 'vote_type')},
            },
        ),
    ]
