# Generated by Django 4.2.6 on 2025-11-04 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chardata', '0010_buildvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chardata.char')),
            ],
            options={
                'indexes': [models.Index(fields=['build', 'ip_address', 'viewed_at'], name='chardata_bu_build_i_b1da74_idx')],
            },
        ),
    ]
