# Generated by Django 4.2.6 on 2025-11-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chardata', '0011_buildview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='char',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='char',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='solutioncounter',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='solutioncounter',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
